### ISSUE TITLE
During the decoding time,where do you use information of response

### ISSUE THREAD

**Issue by yuxinzhang96** [WING-NUS/sequicity#14] opened 2018-11-21 13:56 UTC
In your paper,you say Bt = seq2seq(Bt−1Rt−1Ut|0,0)  but I don't find information of response used during the decoding time in your code.Can you tell me where you use information of response?

**Comment by knmnyn** [comment] 2018-11-22 02:03
Duplicate of #13 

From: @AuCson The ground truth response is directly concatenated to the input, as our baselines also did so. It's a standard practice.

**Closed as completed by knmnyn** 2018-11-22 02:03 UTC
